### ISSUE TITLE
Kaspersky detect this!!

### ISSUE THREAD

**Issue by ghost** [vysecurity/morphHTA#1]
hi ,first thanks for this great tool, but kaspersky total security 2017  detect the morphed HTA files, can reFUD your tool please,thanks

**Comment by vysecurity** [comment]
Ah interesting. Must be because they took my sample from VT :) but I don't think I care enough to change the tool for just 1 vendor. I manually change all my payloads after generation anyways - and so should you. It's only meant to assist :)

**Comment by vysecurity** [comment]
Maybe in the future
