### ISSUE TITLE
HTA File Script Errors

### ISSUE THREAD

**Issue by curi0usJack** [vysecurity/morphHTA#2]
Gave morphHTA a shot with CS's HTA > Executable attack. Confirmed evil.hta works properly. I ran it through morphHTA and got the following error:

![image](https://user-images.githubusercontent.com/5608516/27694913-20337872-5cb3-11e7-9bd1-8b3ac02cb91c.png)

Line 1390 looks like so:

![image](https://user-images.githubusercontent.com/5608516/27694940-319ad362-5cb3-11e7-9473-25b936c826cf.png)

I removed the trailing ampersand and reran the HTA. I got the following:

![image](https://user-images.githubusercontent.com/5608516/27694959-3d356d22-5cb3-11e7-81aa-9832de0f7b97.png)

With line 1558 looking like this:

![image](https://user-images.githubusercontent.com/5608516/27694990-515a2680-5cb3-11e7-88e5-718b81d1a7c9.png)

Finally, just a thought (and I'm probably way off on this), but I don't see how the hta would actually fire the payload. At the bottom of the hta, I'd expect to see an obfuscated call to actually fire the concatenated code. I just see more variable assignments:

![image](https://user-images.githubusercontent.com/5608516/27695056-7b968150-5cb3-11e7-9518-b1b5a180a4b3.png)

Good work! I was just needing some CS obfuscation this morning. :-)

**Comment by vysecurity** [comment]
Hi there,

Yes I think I've seen a few bugs here and there too. Hmmm but it usually works. Regenerate? :)

It only works with the PS evil.hta ATM I think
